### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by conao3** [markuplint/markuplint#104]
Hi, I want to contribute to this project, but I don't familier with Node.

Could you add `CONTRIBUTING.md` for me and other new contributors to get running local tests or something internal information or something prerequirements before send PRs.

**Comment by tyankatsu0105** [comment]
I was just thinking the same thing!

This proposal looks good.
@YusukeHirao 
How about you?

**Comment by YusukeHirao** [comment]
@conao3 
@tyankatsu0105 

Thanks for your idea.
I also kind of noticed that I must, so I will do it.
