### ISSUE TITLE
Ci failed: lerna: not found

### ISSUE THREAD

**Issue by conao3** [markuplint/markuplint#110]
Recently, our CI is failed because `lerna` not found.
https://github.com/markuplint/markuplint/runs/1346474792#step:7:6

How do we handle this?

**Comment by YusukeHirao** [comment]
@conao3 
I discovered the same problem.
I noticed that it skipped phasing the "install dependencies" but I don't why.

@tyankatsu0105 
Do you know why it will skip phasing the "Install dependencies"?
https://github.com/markuplint/markuplint/runs/1346474792

**Comment by tyankatsu0105** [comment]
I'll check that

**Comment by conao3** [comment]
Thanks!
