### ISSUE TITLE
`overrides` option in .markuplintrc overrides not only the explicitly stated rules but also whole set of rules

### ISSUE THREAD

**Issue by tnyo43** [markuplint/markuplint#1119]
- Markuplint version: 3.12.0 (the latest version on August 3, 2023)
- Parser lang: HTML, JSX
- Node.js version: 18.16.0
- OS: macOS

[here is a reproduction](https://github.com/tnyo43/markuplint-overwrite-rules)

## Describe the bug

`overrides` option in .markuplintrc overrides not only the explicitly stated rules but also whole set of rules.

## Code Example

**index.html**
```html
<html></html>
```

### errors occur with rules (expected behaviour)

1. modify the ".markuplintrc" as lint follows:

```json
{
  "extends": [
    "markuplint:recommended"
  ]
}
```

2. run `npx markuplint **/*.html` and you will see something like the following errors.

```bash
<markuplint> error: Require doctype (doctype) /path/to/markuplint-overwrite-rules/index.html:1:1
  1: <html></html>
  2: 
<markuplint> error: Require an element. (Need "title") (permitted-contents) /path/to/markuplint-overwrite-rules/index.html:1:7
  1: <html>headml>
  2: 
<markuplint> error: The "html" element expects the "lang" attribute (required-attr) /path/to/markuplint-overwrite-rules/index.html:1:1
  1: <html></html>
  2: 
<markuplint> error: Require the "meta[charset="UTF-8" i]" element (required-element) /path/to/markuplint-overwrite-rules/index.html:1:7
  1: <html>headml>
  2: 
<markuplint> error: Require the "h1" element (required-h1) /path/to/markuplint-overwrite-rules/index.html:1:1
  1: <html></html>
  2: 
 ELIFECYCLE  Command failed with exit code 1.
```

### overrides one of the errors and no error occurs (unexpected behaviour)

1. modify the ".markuplintrc" as lint follows:

```json
{
  "extends": [
    "markuplint:recommended"
  ],
  "overrides": {
    "./index.html": {
      "rules": {
        "doctype": false
      }
    }
  }
}
```

2. run `npx markuplint **/*.html` and you won't see any error.

## The current behavior

If we use "overrides" option, it seems that a whole set of the rules for that file is overridden.

## The expected behavior

I expect that only the "doctype" rule is overridden. Even in the same file, I still want to apply the other rules, such as "permitted-contents", "required-attr" and so on.

**Comment by tnyo43** [comment]
Now I understand that probably you implemented it intentionally.

https://github.com/markuplint/markuplint/blob/d05bcb8f4a2e024e298a4c1e0d3dd29ab4d1a26b/packages/%40markuplint/file-resolver/src/config-provider.ts#L84-L87

However, I think it would be easy to clutter the configuration file if a whole set of rules is overridden. If we want to override only a single rule for a glob, we need to declare the rest of the rules again.
I really appreciate if the overrides rule is merged with the base rule instead of replace it.

**Comment by YusukeHirao** [comment]
@tnyo43 

Thank you for your report.

I'm honored that you have shown an understanding of the code. As you have mentioned, I too feel that this feature is indeed difficult to use. However, when it comes to handling the configuration file, compatibility is crucial, so I want to proceed carefully. This will likely be addressed after version 5. However, implementing a feature that allows the user to choose between 'complete overwrite' and 'merge' through an option might help solve the issue faster. Please allow me to consider this while referring to the APIs of other tools. Thank you.
