### ISSUE TITLE
file-resolverのtypeのnameがoptionalでない可能性について

### ISSUE THREAD

**Issue by kinetanie** [markuplint/markuplint#1121]
- Markuplint version: `3.12.0`
- Parser lang: HTML
- Node.js version: `20.5.0`
- OS: macOS 

## Describe the bug
`MLEngine.toMLFile`の引数の型である[Target型](https://api.markuplint.dev/types/_markuplint_file_resolver.target)において、nameはstring | undefinedになっていますが、
実際の挙動は、string型かつ、最後に`.html`が付く必要がありそうでした。
## Code Example

```typescript
import { MLEngine } from "markuplint";
import path from "path";
import { promises as fs } from "fs";

const main = async () => {
  // sourceCodeで入力する
  const testFile = await fs.readFile(
    path.resolve(__dirname, "test.html"),
    "utf-8"
  );
  const file = await MLEngine.toMLFile({
    // nameを設定しない or .htmlが付いていないnameを指定する
    sourceCode: testFile,
  });
  // パスを渡してreadFileする
  const file2 = await MLEngine.toMLFile(path.resolve(__dirname, "test.html"));
  
 // コードが渡されているかの確認
  const code1 = await file?.getCode()
  const code2 = await file2?.getCode()

  console.log(code1 === code2, "SAME") // trueになる

  // それぞれインスタンス化する
  const engine = new MLEngine(file!, {
    configFile: path.resolve(__dirname, ".markuplintrc"),
  });
  const engine2 = new MLEngine(file2!, {
    configFile: path.resolve(__dirname, ".markuplintrc"),
  });


  const result = await engine.exec();　// nullになる
  const result2 = await engine2.exec(); // こっちは結果が返ってくる
};
```

## Steps To Reproduce

1. 上記のコードを実行してみてください。環境依存の可能性も捨てきれません。

## The current behavior
`await engine.exec()`の結果がnullになる

## The expected behavior
1 or 2
1. APIドキュメントのTarget型のnameがname: `{string}.html`となる
2. Anonymous Fileとして結果を出力できる

**Comment by YusukeHirao** [comment]
@kinetanie 

報告ありがとうございます。

これはパーサーのデフォルトの設定が由来する挙動ですね。

Markuplintはいろいろなシンタックスを扱うので、標準で全てのファイルをHTMLパーサーに通すわけにはいかないので、内部的に拡張子判定しています。

なので、APIからソースコードだけを渡す場合、明示的なパーサーの指定が必要になります。

```json
{
  "parser": {
    ".*": "@markuplint/html-parser"
  }
}
```

分かりづらい部分ではあると思うので、APIのデフォルトをどう扱うか検討してみます。ありがとうございます。
