### ISSUE TITLE
`wai-aria`ルールの文章で、ARIA in HTMLがドラフトと説明されている

### ISSUE THREAD

**Issue by momdo** [markuplint/markuplint#1123]
## Document or Issue Link

<https://markuplint.dev/ja/docs/rules/wai-aria>では、

> ARIA in HTMLに関しては、@markuplint/html-specに設定値を持っています。またこの仕様はまだドラフトであるため、任意に無効化できます。

と説明されていますが、ARIA in HTML仕様はW3C勧告です。したがって、「ドラフトであるため」という説明は正確ではありません。
（Living Standardのように高速で勧告が更新されてはいますが）

<https://www.w3.org/TR/html-aria/>

**Comment by YusukeHirao** [comment]
@momdo 直します…！
