### ISSUE TITLE
"The #text is invalid element" error when parsing url within SVG's <use>

### ISSUE THREAD

**Issue by ZuBB** [markuplint/markuplint#1261]
- Markuplint version: latest stable, also v4-alpha5
- Parser lang: nunjucks-parser
- Node.js version: `v18.16.0`
- OS: macOS 13.6

## Describe the bug

I am getting the error from subject for the next piece of code inside Django's templates (have a strong feeling Django is not a root cause here)

## Code Example

```html
...
<svg•width="11"•height="19"•viewBox="0•0•11•19"•class="ms-1">
  <use•href="{%•static•'images/icons-test/angle-right.svg'•%}#icon"></use>
...
```

----
<img width="1728" alt="image" src="https://github.com/markuplint/markuplint/assets/597016/45754bb6-964d-4187-9d12-a23069e97972">

**Comment by YusukeHirao** [comment]
@ZuBB 

I'm sorry for the delay in investigating this issue. Like #1349, this also seems to be a problem with the attribute parser. I would appreciate your patience while we work on a solution.

**Comment by ZuBB** [comment]
> @ZuBB
> 
> I'm sorry for the delay in investigating this issue. Like #1349, this also seems to be a problem with the attribute parser. I would appreciate your patience while we work on a solution.

Sure thing. thanks for your response
