### ISSUE TITLE
Remove `@markuplint/create-rule-helper` package from the dependency to reduce the install size

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#1288]
Playgroundを作成する中で、 `npm install markuplint` の実行時間が長いことが少し気になり、依存パッケージの内訳を調べていました。

https://pkg-size.dev/markuplint

上記ツールで確認したところ、 `@markuplint/create-rule-helper` の dependenciesである `typescript`, `prettier` で過半数を占めていました。

create-ruleの機能自体は便利ではあるものの、ビルトインのルールだけ使う場合には使用しない、かつ使うとしても頻繁に実行するものではないため、本体の依存からは外してもよいかもしれません。

```
npx @markuplint/create-rule-helper
```

のような形で、必要なときだけインストールする使い方ができるとよさそうです。

**Comment by kagankan** [comment]
`typescript` が呼ばれているのが `create-rule-helper` だけかと思いましたが、
`cosmiconfig` （TypeScript形式の設定ファイルをサポートするパッケージ）からも呼ばれているので、
軽量化を目指す場合これも剥がす必要が出てきそうでした… 🤔

**Comment by YusukeHirao** [comment]
@kagankan 

```
npx @markuplint/create-rule-helper
```

に任せるのは、これは採用したいですね。

```
npx @markuplint/init
```

とかにしちゃおうかな。

cosmiconfigの工夫は、ちょっとアイデアほしいです。
コア機能なので、現段階だと必須です。

**Comment by kagankan** [comment]
@YusukeHirao 

ご検討ありがとうございます！！

コマンド名（パッケージ名）については、

> `npx @markuplint/init`

だと `npx markuplint --init` と混同しそうなので、
`npx @markuplint/create-rule` ぐらいがいいかなーと思います。


cosmiconfigのほうについてはすみません、勘違いだったので気にしないでいただいて大丈夫です！
`cosmiconfig` の **`peerDependencies`** に `typescript` が指定されているのですが、
それと同時に `peerDependenciesMeta` で `"optional": true` が設定されているので、  `typescript` はデフォルトではインストールされませんでした。
（実際に `npm install cosmiconfig` を実行してみましたが、 `typescript` はインストールされませんでした）

なので、 `@markuplint/create-rule-helper` を依存から外すことができれば、インストールサイズは大きく削減できそうです。

**Comment by YusukeHirao** [comment]
@kagankan 

ああ、自分も`create-rule`と`init`で勘違いしてました。

やるなら今のうちだなぁ…v4の正式リリースの前に完全なブレイキングチェンジとしてやってしまいたいかも。

**Comment by kagankan** [comment]
@YusukeHirao 
ご対応ありがとうございました！
この変更によって、 `markuplint` 単体をインストールしたときのサイズがおよそ1/3に削減されたようです 🎉 


https://pkg-size.dev/markuplint@4.0.0-alpha.6
72MB
![image](https://github.com/markuplint/markuplint/assets/34136752/0d1c1ea8-a423-45c2-ac2d-7d9c61cf96eb)

https://pkg-size.dev/markuplint@4.0.0-dev.10
26MB
![image](https://github.com/markuplint/markuplint/assets/34136752/5e89bb6a-5b19-4bd7-96e3-1922390f7b31)
