### ISSUE TITLE
[playground] Shorten URL hash

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#1290]
`lz-string` will be usefull.
https://www.npmjs.com/package/lz-string

it is used in typescript-eslint playground.
https://github.com/typescript-eslint/typescript-eslint/blob/f5e712b6e5ce524071ee5d13ef15fcfbf7f3e958/packages/website/src/components/hooks/useHashState.ts#L12

**Comment by YusukeHirao** [comment]
@kagankan 

Nice! Let's adopt this way :+1:

**Comment by kagankan** [comment]
Fixed in #1290
