### ISSUE TITLE
Enable to use default rules and config detection feature via Node.js API

### ISSUE THREAD

**Issue by ktsn** [markuplint/markuplint#13]
Hello!

I encounters a problem which I cannot utilize default rules and default config detection on easy way during I'm writing [a gulp plugin](https://github.com/ktsn/gulp-markuplint) to use markuplint in gulp task.

The Node.js APIs (`verify` and `verifyFile`) looks to assume the users to specify ruleset and rules by themselves. It would be a bit hard for a plugin devs to use the APIs.

[I'm executing `markuplint` command via CLI](https://github.com/ktsn/gulp-markuplint/blob/master/src/index.ts#L55) to use such features. However, it decreases the flexibility of the tool.

Can we includes the features in the Node.js APIs like eslint's [`CLIEngine`](https://eslint.org/docs/developer-guide/nodejs-api#cliengine) or expose them as a separated APIs so that plugin devs easily write full-featured markuplint plugins?

**Comment by YusukeHirao** [comment]
@ktsn  ありがとうございます。

込み入った話になりそうで、それだと英語は無理なので日本語で返事させてもらいますね、すみません。

今の状態、自分でもNode.jsで利用していて（VS Code拡張版の開発で）不便を感じているのでAPIの改善は計画しています。おっしゃる通り機能の分離はなるべく対応したいと考えています。ルールとコンフィグファイル読み込み周りは全然ダメダメなので、Node.jsのAPIも、CLIももうちょっとなんとかします。CLIEngine参考にしますね。

ちょうどv1に向けて再設計とmonorepo化と進めていたので、Issue本当に嬉しいです。

**Comment by ktsn** [comment]
回答ありがとうございます！
ちょうど再設計中だったんですね。Node.js API が簡単に使えるようになればいろいろと派生ツールの幅が広がりそうなので、楽しみにしています 👍

**Comment by YusukeHirao** [comment]
@ktsn 
長く時間が空いてしまいましたが、提案していただいたESLintを参考にAPIを再設計して `v1.0.0` で改修ができました。
実装部分: https://github.com/markuplint/markuplint/blob/master/packages/markuplint/src/lint.ts#L9-L61
ドキュメント: https://markuplint.dev/api-docs#options

ありがとうございました。
また是非、フィードバックをよろしくおねがいします。
