### ISSUE TITLE
Remove `node-fetch` package from the dependency

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#1336]
#1288 の改善後、インストールサイズの中で次に大きな割合を占めているのが `web-streams-polyfill` パッケージです。

https://pkg-size.dev/markuplint@4.0.0-dev.20

![image](https://github.com/markuplint/markuplint/assets/34136752/f371ccbf-4acd-4e54-a5d3-87234ab9baf2)

これについても依存から外すことができればインストールサイズを削減できるため、削除できないか検討したいです。
（削減できなくても大きな問題はないのですが、必要性の低いパッケージであれば検討したい、という程度です）

依存関係としては
markuplint > node-fetch > fetch-blob > web-streams-polyfill
となっており、 `node-fetch` の使用をなくすことができれば削減できそうです。

`node-fetch` が使用されている箇所は `packages/markuplint/src/cli/init/get-default-rules.ts` で、ビルトインルールの取得およびカテゴリ分けに使われています。

https://github.com/markuplint/markuplint/blob/dev/packages/markuplint/src/cli/init/get-default-rules.ts

用途を見た感じ、fetch を経由せずとも `@markuplint/rules` から取得する実装にできるのではないか（かつ、そうあるべきではないか）と思っていますがいかがでしょうか？

実装イメージのドラフトPRを立てていますので、懸念等あればご指摘ください！
https://github.com/markuplint/markuplint/pull/1335

**Comment by YusukeHirao** [comment]
@kagankan 

とてもいいと思います！
`meta.category`を増やすのはv4リリースまでに整理しておきたいので、早めに対応したいです。
