### ISSUE TITLE
[website] Code block `class` disabled due to dependency update

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#1355]
@kagankan 

classが無効になって歯車アイコンやシンタックスハイライトが効かないようになってしまいました。
すみません。不注意でした。`dev`ブランチのみです。

![classが無効になって歯車アイコンやシンタックスハイライトが効いていない様子](https://github.com/markuplint/markuplint/assets/953956/279ed2f1-dde2-44b4-9ebf-fd91beff2289)

**Comment by kagankan** [comment]
@YusukeHirao 
報告ありがとうございますー！　確認します

classじゃなくてカスタムプラグインにしたほうがよいかも、と以前考えていたので、これを機に実装方法も含めて検討しようと思います
