### ISSUE TITLE
[Website] Build failure due to dependent on `@markuplint/rules`

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#1472]
新しくルールを追加したPRで、ウェブサイトのビルドに失敗します。

新しくルールを追加すると `packages/@markuplint/rules` に新しいディレクトリやファイルが作られ、ウェブサイトはそれを見てルールページを生成しますが、一方でnpmに公開された`@markuplint/rules`も`meta`を見るために参照します。

新ルールを追加した開発リポジトリの状態と公開されたパッケージで不整合が発生するため、依存関係を片方に寄せたほうが良さそうです。

失敗したCI: https://github.com/markuplint/markuplint/actions/runs/7869017722/job/21467271620?pr=1471

**Comment by YusukeHirao** [comment]
npmパブリッシュ後も、ウェブサイトのdependenciesがパッチまでバージョンが固定されているのとyarn.lockファイルも作られているため、やはり新しいルールを参照できずに失敗しますね。

`@markuplint/rules`を使わずに、ファイルを見に行ったほうがいいと思います。
`lib/`のJSファイルを見に行くためにはビルドが必要になってしまうので、`meta.category`を`schema.json`持っていく工夫が必要かもしれません。

**Comment by kagankan** [comment]
反応遅くなりました 🙏 
不整合どうにかしないとなので解消方法考えます…！

>meta.categoryをschema.json持っていく工夫が必要かもしれません。

websiteのビルドに必要な情報としてはたしかにschema.jsonに寄せたほうが楽ではあるのですが、以前 [markuplint本体の依存パッケージが大きい問題](https://github.com/markuplint/markuplint/issues/1336) の解消のために [schema.jsonからindex.ts に移動した](https://github.com/markuplint/markuplint/pull/1335) 経緯があるので、これを戻すのはあまりしたくないのですよね…
なのでwebsiteのためにschema.jsonに記述する場合、index.tsと二重管理になってしまうかなと思っています

他のライブラリでの例も見てみて、方法考えます
