### ISSUE TITLE
[feat] Can you please provide sync API with async together?

### ISSUE THREAD

**Issue by JounQin** [markuplint/markuplint#153]
<del>
I'm trying to integrate this package with ESLint together, and found that I have to resolve `config`, `rules` and `locale` manually to use `verify` API.
</del>

<del>
I know I can follow https://github.com/markuplint/markuplint/blob/master/packages/markuplint/src/lint.ts#L64-L66 as example to get the necessary parameters quickly, but it would be better to provide a simpler API to do this job.
</del>

Maybe I should `exec` API instead.

```ts
const resultInfos = await exec({
  sourceCodes: sourceCode,
  names: filename,
  fix: true,
})
```

---

And there is no synchronized API provided, which is incompatible with ESLint currently.

So, I hope a synchronized API.

Thanks for your great work!

**Comment by JounQin** [comment]
I'm glad to add sync API when I'm free if you agree.

**Comment by YusukeHirao** [comment]
@JounQin 
Please wait for the completion of ESLint improvement.
Thank you for the suggestion.

I'm closing.
