### ISSUE TITLE
[rule-textlint] use `textlint` module instead to load `.textlintrc` automatically

### ISSUE THREAD

**Issue by JounQin** [markuplint/markuplint#161]
It seems too verbose to use `.markuplintrc.js` (json config is not supported in current case)

```js
const path = reuqire('path')

module.exports = {
  rules: {
    textlint: {
      option: {
        rules: [
          {
            ruleId: 'prh',
            rule: require('textlint-rule-prh'),
            options: {
              rulePaths: [path.resolve(__dirname, '../', 'prh.yml')],
            },
          },
        ],
      },
    },
  },
}
```

Proposal:

```js
const path = require('path')

const { Config } = require('textlint/lib/config/config')
const { TextLintEngine } = require('textlint/lib/textlint-engine')

const main = async filename => {
  const lintEngine = new TextLintEngine(
    Config.initWithAutoLoading({
      cwd: path.dirname(filename), // it will still find up configs above dirname
    }),
  )

  const result = await lintEngine.executeOnText(
    /* HTML */ `
      <p>a,b,c,d,e,f,g,h,i</p>

      <h1>my name</h1>
      <h1>my name</h1>
    `,
    path.extname(filename),
  )

  console.log(JSON.stringify(result, null, 2))
}

const filename = path.resolve(__dirname, 'textlint/test.html')

main(filename)
```

So that `.markuplintrc` json file will be supported.

I'm glad to raise a PR if you agree.

**Comment by YusukeHirao** [comment]
@JounQin 

Thanks, I remembered I want it too.
But we must think about API.
I don't want to change the interface of the textlint configuration.

**Comment by JounQin** [comment]
@YusukeHirao 

We can add a new option `textlintrc?: boolean` which is true by default. And when `option` is provided, it defaults to be `false`, when user use `option` with custom `textlintrc: true`, we could emit a warning and only use `option`.

**Comment by YusukeHirao** [comment]
@JounQin 

Oh! Now I know.

It doesn't interfere with the `option` props.
Nice, let's do with your concept.

**Comment by JounQin** [comment]
@YusukeHirao 

I found that:

1. I misunderstood `config.option`, I thought we could do `config.textlintrc` previously. So I want to change `type Option = Partial<Parameters<TextlintKernel['lintText']>[1]> | true`
2. There is no file info accessible at all in `verify` or even `document`, so I need to add it into `document`

How do you think?
