### ISSUE TITLE
tabindexに関連したルールを個別ルールに切り出し

### ISSUE THREAD

**Issue by ken7253** [markuplint/markuplint#1730]
## 概要

現在`tabindex`属性に関するルールは、プリセットルール`markuplint:a11y`によって下記のように設定されているかと思われます。
https://github.com/markuplint/markuplint/blob/5fd0c5191d0d614b78720e060c82564f2771ecb9/packages/%40markuplint/config-presets/src/preset.a11y.json#L29-L32

より細かいケアを行うために、新しく`tabindex`に関するルールに切り出したほうがより良くなるのではないかと考えました。

## 提案の理由について

モチベーションとしては大まかに２つ理由があります。

### dialog要素のケア

[Living Standardに記載されている](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element:~:text=The%20tabindex%20attribute%20must%20not%20be%20specified%20on%20dialog%20elements.)ように`dialog`要素に対して`tabindex`属性を付与することは禁止されています。

今後`popover`などの普及により`dialog`要素の利用が増える可能性が高いため、このルールの追加の必要性があると感じています。

### より細かい説明

> 属性「tabindex」は「-1」「0」のいずれかである必要があります。

現在プリセットを利用した場合は上記のようなエラーが表示されますが、`dialog`要素に対してのエラーを出し分けるためにも新しいルールを作成したほうがいいのではないかと考えました。

## お願いしたいこと

ひとまず近日中に一度PRを立てようと思うので、もしこの提案に関心を持っていただけるようでしたらレビューをお願いしたいです。

**Comment by YusukeHirao** [comment]
@ken7253 

すばらしい提案ありがとうございます。

`dialog`での利用ですが、これは`tabindex`属性の「扱い方」ではなく「HTMLの仕様で違反」にあたるので、[invalid-attr](https://markuplint.dev/ja/docs/rules/invalid-attr)で対応するべきだと思いました。というのも、スキーマ上[`noUse` というプロパティをつけている](https://github.com/markuplint/markuplint/blob/e6e78681f89d72aff061d75d170d43b48dda9984/packages/%40markuplint/html-spec/src/spec.dialog.json#L18-L21)のですが、これは私の完全な実装漏れですね。`invalid-rule`で`noUse`を見るように修正をしたいと思います。（Issue化しました: #1734）

その上で、`tabindex`で他に細かくルールを調整する必要があり、ルール化したほうがよさそうでしたら教えて下さい。

**Comment by ken7253** [comment]
ご確認ありがとうございます！

> dialogでの利用ですが、これはtabindex属性の「扱い方」ではなく「HTMLの仕様で違反」にあたる

そうなんですね！こちら自分もちょっと勘違いしていました…！

> その上で、tabindexで他に細かくルールを調整する必要があり、ルール化したほうがよさそうでしたら教えて下さい。

そうするとそこまで個別ルールにするモチベーションは無いのでissueはCloseしていただければと思います！

#1734 もし時間の余裕があれば自分で対応させていただきたいです…！

**Comment by YusukeHirao** [comment]
@ken7253 

> https://github.com/markuplint/markuplint/issues/1734 もし時間の余裕があれば自分で対応させていただきたいです…！

もちろん！大歓迎です！

**Comment by YusukeHirao** [comment]
Resolved on https://github.com/markuplint/markuplint/pull/3215
