### ISSUE TITLE
CLI fails silently on errors

### ISSUE THREAD

**Issue by RobertAKARobin** [markuplint/markuplint#1824]
- Markuplint version: `4.9.0`
- Parser lang: HTML
- Node.js version: `20.11.0`
- OS: macOS

## Describe the bug

The Markuplint CLI reports a "pass" in conditions that should instead report an error, such as:

- On `throw new Error`
- When a rule name is misspelled
- When a plugin name is misspelled

## Code Example or Playground URL

https://github.com/RobertAKARobin/markuplint-issues

## Steps To Reproduce

1. Clone https://github.com/RobertAKARobin/markuplint-issues
2. `npm i`
3. `npm run lint`
4. Observe Markuplint reports a pass
5. In `markuplint.config.js` and `rules/my-rule.js`, comment in the commented-out lines, which contain the error conditions described above
6. `npm run lint`
7. Observe Markuplint still reports a pass

## The current behavior

Markuplint reports a pass.

## The expected behavior

Markuplint should report an error, or a failure.

**Comment by YusukeHirao** [comment]
@RobertAKARobin 

I agree that this issue is important and will work towards resolving it. I will ensure that the CLI correctly reports errors. I will update here as soon as there is progress.
