### ISSUE TITLE
中身が空で問題ないパルパブルコンテンツが `no-empty-palpable-content` で警告される

### ISSUE THREAD

**Issue by SaekiTominaga** [markuplint/markuplint#1948]
- Markuplint version: `4.9.2`
- Parser lang: HTML

Bug Report として提出していますが、とくに最後のもの（`<template>` 関係）は議論の余地があるだろうとの認識です。

## `output` 要素

`output` 要素は主に JS で操作するものであり、その使用方法からすると空であり得ます。

[ソースコード](https://github.com/markuplint/markuplint/blob/dev/packages/%40markuplint/rules/src/no-empty-palpable-content/index.ts)を見ると `textarea` 要素を例外的に除外していますが、理由付けとしてはこれと同様になるかと思います。

## `audio`, `video`, `canvas` 要素

これらは [HTML 仕様](https://momdo.github.io/html/dom.html#palpable-content)の Note にて以下の記述があります。

> パルパブルコンテンツは、子孫の空でないテキスト、またはユーザーが聞くことができるもの（audio要素）、もしくは見ることができるもの（video、img、canvas要素）、もしくは他の方法で相互作用することができるもの（たとえば、対話的なフォームコントロール）のいずれかを提供することにより、要素を空でないものにする。

この Note は https://github.com/whatwg/html/pull/24 で追加されたもので、議論の元は https://www.w3.org/Bugs/Public/show_bug.cgi?id=28728 になります。

> An element contains palpable content if it either has descendant nodes with text that is not inter-element whitespace, or if it has descendant nodes that are images (img and canvas elements), or audio or video elements, or non-hidden form controls.

どちらの表現からしても、`<span>` などは子孫が空でないことが必要ですが（厳密には例外あり）、`<audio>`, `<video>` ,`<img>`, `<canvas>` は要素がそれであるというだけで追加の条件なしに（＝中身が空であっても）「要素が空でない状態を示す」ものと解釈できます。

最新の Markuplint@4.9.2 では "no-empty-palpable-content" を有効にすると中身が空の `<video></video>` と `<canvas></canvas>` が警告されるため、これは動作バグということになるかと思われます。

`<audio></audio>` は警告されませんでしたが、この辺の判定をどこでやっているかソースコードを追い切れなかったので、これが意図した動作なのかは判断できませんでした。

`<img>` はそもそも void 要素の判定で除外されているので問題ありません。

## `template` 要素の子孫と親

これは仕様云々よりも使い方の問題になりそうですが、こういうマークアップをすることがあります。

```html
<ul>
	<template>
		<li></li><!-- JS で中身をつっこむ -->
	</template>
</ul>
```

これは `<li>` が空であると怒られてしまうのですが、問題のないマークアップだと思います。

ただしスクリプト無効環境や、JS が何らかの理由でエラーになった場合などは結果として中身が空の `<ul></ul>` と同義になってしまうので、リスクあるマークアップだという考え方もできるかもしれません。

また、もしこの警告を除外するならば `no-empty-palpable-content` ルールに限らず、例えば

```html
<template>
	<time datetime=""></time><!-- JS で中身と属性値をつっこむ -->
</template>
```

で `datetime` 属性が `invalid-attr` エラーになるのも防がなければならず、また `<template>` の親要素も `wai-aria` ルールに引っ掛かることがあるため、影響範囲の大きい話になってきそうです。

自分は以下の設定で自己対処しており、それで特に困ってはいませんが、一応こういう事象も発生しているということで。（強く修正を求めるものではありません）

```
nodeRules: [
	{
		selector: 'template *',
		rules: {
			'no-empty-palpable-content': false,
			'require-accessible-name': false,
		},
	},
	{
		selector: ':has(> template)',
		rules: {
			'wai-aria': false,
		},
	},
],
```

**Comment by YusukeHirao** [comment]
@SaekiTominaga 

いつもありがとうございます。

`<video></video>`と`<canvas></canvas>`はおっしゃるとおりバグにあたると思うので修正します。

`template`関連の扱いは、プロジェクトの指針にされるでしょうし、空であることが意図したものであるかReactやVueのような宣言的シンタックス以上に推論できないものなので、ドキュメントのユースケースとしてどこかのタイミングで追記しようかと思います。ご指摘はご尤もで、私自身は気が行き届いていなかったところなので大変助かります。
