### ISSUE TITLE
playground を独立したリポジトリに移動する

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#2008]
プレイグラウンドサイトのソースファイル群は、このリポジトリ内の `playground` ディレクトリとして配置されています。
しかし、現在では `playground` ディレクトリ内のコードは他のディレクトリ（`packages` など）には依存していないため、同じリポジトリで管理する必要はなくなっています。

同じリポジトリで管理されていること自体に問題があるわけではありませんが、

- プレイグラウンドの変更をしたいだけの場合でも、他のディレクトリのためのパッケージをインストールする必要がある
- Issue Template, PR Templateが共有になるため、これらがプレイグラウンドにとっては合わない内容になる

などの問題をはらんでいます。

同一リポジトリに配置する必然性がなければ、playgroundを独立したリポジトリに移動したほうがよいかもしれません。

（ちなみに、本来websiteも同様に独立したリポジトリにできるとよさそうですが、websiteはpackages配下のファイルを参照しているため分離が難しいと考えています）

**Comment by YusukeHirao** [comment]
賛成です。
Playground側でバージョンタグを選択できるので問題ないと思います。

**Comment by YusukeHirao** [comment]
準備しました。
https://github.com/markuplint/playground

**Comment by kagankan** [comment]
@YusukeHirao 
早速ご準備ありがとうございます！

リポジトリ名について、 `markuplint-playground` にしておきたいのですがいかがでしょう？
markuplintのorganization配下にあるので自明ではあると思いつつ、フォークしたときなど、リポジトリ名単体で表示されるときのことを考えるとリポジトリ名に `markuplint-` を含めておきたいです。

移行作業は追って私の方で対応しますね。

**Comment by YusukeHirao** [comment]
変更しました！
https://github.com/markuplint/markuplint-playground

**Comment by kagankan** [comment]
@YusukeHirao 

markuplint-playground リポジトリにファイルを追加し、こちらのリポジトリからデプロイされるようにNetlifyの設定を変更しました！
デプロイ後の動作も確認済みです。
https://playground.markuplint.dev

後ほど、markuplint（本体）リポジトリからplaygroundのファイルを削除するPRを作成します。
