### ISSUE TITLE
.markuplintrcでプラグインを指定すると、CLIではエラーにならないがVSCode拡張機能でエラーになる

### ISSUE THREAD

**Issue by nagashimam** [markuplint/markuplint#2044]
- Markuplint version: `4.7.5`
- VSCode version: 1.92.2
- Parser lang: HTML
- Node.js version: `20.11.1`
- OS: macOS

## バグの詳細

プラグインを使うように設定した場合、CLI(`npx markuplint XXX.html`)からは正常に実行できますが、vscode-markuplintをインストールしたVSCodeで同じHTMLファイルを開くと「XXXXXX could not be cloned」というエラーが表示されます。XXXXXXは`async (context) => await verify(context, config) `のように、プラグインのverifyに指定した関数が表示されます。

![上記のエラーがVSCode上で出ているスクリーンショット](https://github.com/user-attachments/assets/d43b741a-0e69-4b29-807e-9c946610270b)

## 再現手順

- `git clone https://github.com/nagashimam/vscode-extension-error.git`
- `cd vscode-extension-error`
- `npm ci`
- `npx markuplint src/index.html`
  - これは正常に終了します
- `code src/index.html`
  - エディター上にエラーが表示されます

この事象は`~/.vscode/extensions/yusukehirao.vscode-markuplint-4.7.5/node_modules/@markuplint/esm-adapter/esm/index.mjs`の

```
engine.on('config', (...params) => {
  parentPort.postMessage({
    uid,
    method: 'log:config',
    data: params,
  });
});
```
を
```
engine.on('config', (...params) => {
  parentPort.postMessage({
    uid,
    method: 'log:config',
    data: JSON.parse(JSON.stringify(params)), // この行を修正
  });
});
```
と変更すると発生しなくなります。

## 現在の挙動

CLIからは正常にチェックできるHTMLをVSCode上で開くとエラーになる。

## 期待される挙動

CLIと同じ結果がVSCode上で表示される

## 原因

Markuplintが設定を読み込むと、esm-adapterがparentPort.postMessageで設定内容を[拡張機能に通知](https://github.com/markuplint/markuplint/blob/dev/packages/%40markuplint/esm-adapter/esm/index.mjs#L113)しています。

プラグインを使う設定になっている場合、関数が`params[1].plugins[0].rules[XXX].verify`に設定されます(XXXはプラグインで使用するルールの名前)。関数は`postMessage`で送信できないため、上記のエラーになります。

## 修正案

再現手順に書いた通り`JSON.parse(JSON.stringify(params))`のように関数を文字列にすると発生しなくなります。この修正で差し支えなければPRを作成しますが、[vscode/test](https://github.com/markuplint/markuplint/tree/dev/vscode/test)の内容は修正必要でしょうか。

**Comment by YusukeHirao** [comment]
@nagashimam 

確認が遅れてごめんなさい。やっと理解しました。
postMessageの関数オブジェクトのまま渡せない問題っすね…。

PR貰えると嬉しいです。テストはほしいですね。こちらで準備しなくても再現して確認できるなら助かります。

**Comment by YusukeHirao** [comment]
VS CodeがESMに対応して`postMessage`は使わなくなったので対応不要となりました。 #2170
