### ISSUE TITLE
現在の設定を確認するためConfigを出力するコマンドまたはオプションがほしい

### ISSUE THREAD

**Issue by yosukedoke** [markuplint/markuplint#2136]
導入している際に設定が思うようにいかず調査に時間がかかったため、現在のrulesなどの設定が有効になっているか確認する方法がほしいです。

ESLint でいう `--print-config` オプション、TSCでいう `--showConfig` に相当する機能です。
https://zenn.dev/nananaoto/articles/9968d8f3966e90a46229
https://www.typescriptlang.org/docs/handbook/compiler-options.html

自分の場合は `.markuplintrc.ts` に vue の parser, specs を導入したうえで `{ extends: ['markuplint:recommended-vue'] }` をベースに、プロジェクト固有の事情で いくつかのルールをOFFにしたかったのですが、 `required-attr` と `invalid-attr` がどうしても無効にできませんでした。
暫定的には `{ nodeRules: { selector: '*'. rules: { /* some rules */ } } }` という設定で強引に上書きして解決しました。

フィードバックを行うにあたって、原因がライブラリ側にあるのか設定にあるのか、仕様理解の問題なのか判断がつかないため、まずはこのあたりのデバッグを行うにあたって表題の機能を提案します。

ちなみに、おそらくバグというより、extendsにあるrecommendedの指定でセレクタを使われている場合に単純に `rule-name: false` で無効にできないのではと思いましたが、調査したりコードの把握に時間がかかりそうだったので取り急ぎ。

**Comment by YusukeHirao** [comment]
@yosukedoke 

ありがとうございます。これは私も欲しいので検討します。

普段は
```sh
$ DEBUG=* markuplint './path/to/**/*'
```
で覗いてましたが、効率悪いのは自覚していたので、近い内に実装したいと思います。

**Comment by yosukedoke** [comment]
@YusukeHirao ありがとうございます！これでこちらの検証も行ったうえで何かあればフィードバックします！
