### ISSUE TITLE
Vueのビルトインコンポーネントをlowercaseで記述すると`permitted-contents`ルールでエラーが出る

### ISSUE THREAD

**Issue by ekrc-1** [markuplint/markuplint#2186]
- Markuplint version: `4.11.1`
- Parser lang: Vue
- Node.js version: `20.18.0`
- OS: Debian GNU/Linux 12

## Describe the bug
Vueの[ビルトインのコンポーネント](https://ja.vuejs.org/api/built-in-components)をlowercaseで記述しているとき、`permitted-contents`ルールでエラーが出ます。  

以下のいずれかに合致するケースでは再現しません。
*  キャメルケース(e.g. `<Transition>`)で記述されている場合
* ケバブケース(e.g. `<transition-group>`)で記述されている場合

## Code Example or Playground URL

`index.vue`:
```vue
<template>
  <div>
    <transition>
      <p v-if="show">hello</p>
    </transition>
  </div>
</template>

```

`.markuplintrc`:
```
{
  "extends": ["markuplint:recommended"],
  "parser": {
    "\\.vue$": "@markuplint/vue-parser"
  },
  "specs": {
    "\\.vue$": "@markuplint/vue-spec"
  }
}
```

https://playground.markuplint.dev/#N4Igxg9gdgZglgcxALhMAOlABF9ICmAHgC75QAmAznslgNp4C2AhgE4DWArgA4A2cUYslb5IjRmXL5yeALoAaTDjzc2lfKxpYM2HLhDpD6AHQA3TvgAkWvAAEWHHv0EB6c-gC0q1us0HdAL6KuniU3KLUKNpKenhGJu7WUXYOXHwCxG4WHmGicYGYASDy4BBSAGJwvPgAKgCe4SggZhbFpVJNADykjHzMpAB8MZ3kcKZDujjdrMxQlHDEcNATenqd3FimHnAwALyhABYQAO54Awf4vLwQnS7cK2suxDNzC0tQD7ej45i3PX2DTAgAJAA

## 再現手順 
1. `markuplint:recommended`または `markuplint:recommended-vue`をプリセットに指定する
2. parser, specsにそれぞれ`@markuplint/vue-parser`, `@markuplint/vue-spec`を指定する
3. `div`等の配下にVueのビルトインのコンポーネントを lowercase で記載する

## 現在の動作
```
Error
このコンテキストでは、要素「div」に要素「transition」を含めることはできません (permitted-contents) [3:5]
```

## 期待される動作
```
No problems found.
```

## 補足
Vueの[ビルトインのコンポーネント](https://ja.vuejs.org/api/built-in-components)の一覧は以下です:
* [`<Transition>`​](https://ja.vuejs.org/api/built-in-components#transition)
* [`<TransitionGroup>`](https://ja.vuejs.org/api/built-in-components#transitiongroup)
* [`<KeepAlive>`](https://ja.vuejs.org/api/built-in-components#keepalive)
* [`<Teleport>`](https://ja.vuejs.org/api/built-in-components#teleport)
* [`<Suspense>`](https://ja.vuejs.org/api/built-in-components#suspense)

いずれもキャメルケースまたはケバブケースで記載した場合、`permitted-contents`ルールのエラーは再現されません。

関連: https://github.com/markuplint/markuplint/issues/482#issuecomment-1133583111

**Comment by YusukeHirao** [comment]
@ekrc-1 報告ありがとうございます。

これはMarkuplintの仕様です。

1. ハイフンを含まないlowercaseは基本的にHTMLネイティブ要素として識別する
2. その場合、HTML Standardにない要素も未知のHTMLネイティブ要素と解釈する
3. ハイフンを含むものはHTML Standardに則ってカスタム要素として解釈する
4. Vueを含むコンポーネントライブラリでもこの点を考慮して独自コンポーネントはパスカルケースを推奨している（参考: https://ja.vuejs.org/guide/components/registration#component-name-casing ）
5. Markuplintでは、未知のネイティブHTML要素を評価する必要があるため、パスカルケースではない名前のタグはそのように解釈する
6. `<transition>`は未知のHTML要素と解釈したため、div要素のコンテキストで許容されていないと評価される

ご理解ください。

ちなみに実装はここです。

https://github.com/markuplint/markuplint/blob/8afbfba54f99fddf5cd5a27aa8ea288ed1d4d30c/packages/%40markuplint/vue-parser/src/parser.ts#L260-L288

**Comment by ekrc-1** [comment]
@YusukeHirao   
丁寧なご説明ありがとうございます。Markuplintの仕様について理解しました。
ご対応に感謝いたしますmm
