### ISSUE TITLE
Markuplint not added to .bin folder after installation in 1.0.0-alpha

### ISSUE THREAD

**Issue by SylviaP666** [markuplint/markuplint#22]
Terminal shows `markuplint not found` after install 1.0.0-alpha.7, and there is no markuplint folder under `node_modules/.bin/`. 
Version `0.32.0` doesn't have this issue.

**Comment by YusukeHirao** [comment]
Thanks for the feedback.

Fix this issue. Release `v1.0.0-alpha.12`.
