### ISSUE TITLE
Supporting for camelCase with react code

### ISSUE THREAD

**Issue by itwillrain** [markuplint/markuplint#2223]
reactでcamelCaseで記載すると、エラーが誤検知さえているようです。

設定ファイルは下記になります。

```ts
import type { Config } from '@markuplint/ml-config';

const config: Config = {
  // テストファイルやストーリーファイルを除外
  excludeFiles: ['/**/*.stories.tsx'],
  extends: ['markuplint:recommended-react'],
  parser: {
    '.[jt]sx$': '@markuplint/jsx-parser',
  },
  specs: {
    '.[jt]sx$': '@markuplint/react-spec',
  },
};

export default config;
```

実際のコード

```tsx
<meta httpEquiv="x-ua-compatible" content="ie=edge" />
```

ご検知される内容は下記です。

```shell
 error: 属性「httpequiv」は許可されていません (invalid-attr)
 error: 属性「content」は未許可です (invalid-attr)
 error: 要素「meta」には属性「http-equiv」が必要です (required-attr) 
 error: 要素「meta」には属性「itemprop」が必要です (required-attr)
 error: 要素「meta」には属性「name」が必要です (required-attr) 
```

**Comment by YusukeHirao** [comment]
@itwillrain ありがとうございます。バグですね。直します。

再現: [https://playground.markuplint.dev](https://playground.markuplint.dev/#N4Igxg9gdgZglgcxALhMAOlABF9ICmAHgC75QAmAznslgNp4C2AhgE4DWArgA4A2cUYslb5IjRmXL5yAWhHMwxPAF0ANJhx5ubSvlY0sGbDlwh059ADoAVpUIASA3gACLDj36CA9LcIztrLr6ZsYAvurGeJTcotQohhomeBZWvo7xLm5cfALEXvKKMtGiyWGYoZggquAQUgBicLz4ACoAnjEoIDZ2VTVSnUTcEKzEWJBQlKMAwhCMQ1BkowC8WAAUwFj8k6pYcORYoQCUWEsAfAnGIsScrNiriTgAPAAWxIy8pw8mL-jM5J-GEzfCTEZhYV7EbgAUQAjpw4AA3JZ4PycZgyMTaYhwABGTTwY2gpEEyJAcHwS2kCHwBK8AKBTy8z1+-y+TxxtVap0eXg55C5Xx5r3e9KwhwA3OVJVAQKEgA)
