### ISSUE TITLE
`extends` from sharable npm package is not supported anymore in 2.0

### ISSUE THREAD

**Issue by JounQin** [markuplint/markuplint#403]
The following used to work in 1.0

```jsonc
// .markuplintrc
{
  "extends": "@1stg/markuplint-config/angular"
}
```

My temporary workaround:

```js
// .markuplintrc.js
module.exports = require('@1stg/markuplint-config/angular')
```

**Comment by YusukeHirao** [comment]
@JounQin Thank you for the report.
Please a moment because I will inspect it.

**Comment by JounQin** [comment]
https://github.com/markuplint/markuplint/blob/b76084dbdb538119a29fd07b19110ef7d3a44670/packages/%40markuplint/file-resolver/src/config-provider.ts#L172-L174

It is thrown here for now.

**Comment by YusukeHirao** [comment]
@JounQin Thank you!

I fixed it.
Try it on `markuplint@2.2.1-dev.20220307.0`.
