### ISSUE TITLE
Fix the setting of Windows OS test on GitHub Actions

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#411]
I don't know why it always fails.

**Comment by kagankan** [comment]
@YusukeHirao 
I found a solution to solve it.
To change `windows-latest` to `windows-2019` .

I'll make a PR soon.

## Details

- `windows-latest` currently uses Windows Server 2022
https://github.com/actions/virtual-environments/issues/4856
- Only Visual Studio (VS) 2022 is installed on Windows Server 2022
- node-gyp7.1.2 fails with VS 2022
https://github.com/markuplint/markuplint/runs/6024014943?check_suite_focus=true#step:5:61
- `windows-2019` (Windows Server 2019  with VS 2019) works correctly

>Our policy is installing one VS version per platform. On Windows Server 2022, we install only VS 2022 (it is in Preview for now but will be released in future).
>If your use-case requires using VS 2019, continue using Windows Server 2019 image. We don't have plans to deprecate it in near future.
>https://github.com/actions/virtual-environments/issues/3949


## Notes

I wish I could solve it by using windows-latest and setup-mesbuild (https://github.com/microsoft/setup-msbuild/) to use VS 2019, or updating version of node-gyp used in test, but I don't know how to do that.

**Comment by YusukeHirao** [comment]
@kagankan 

Awesome! Thank you for PR!
