### ISSUE TITLE
feature: Be able to determine image extensions

### ISSUE THREAD

**Issue by yamanoku** [markuplint/markuplint#412]
```json
{
    "rules": {
        "required-attr": true,
    },
    "nodeRules": [
        {
            "tagName": "img",
            "rules": {
                "required-attr": [
                  "alt",
                  "srcset"
                ]
            }
        }
    ],
}
```

I operate markuplint with the above rules.
In the above rule, we set src and `srcset` for `img`, but I am hoping that we can avoid setting `srcset` for svg file.

```html
<!-- no error -->
<img src="hoge.png" srcset="hoge.png 1x, hoge@2x.png 2x, hoge@3x.png 3x" alt="png image">

<!-- error -->
<img src="hoge.svg" alt="svg icon">
```

I would like to see a setting that sets the extension of the image and does not make an error if that file is used.
What do you think?

**Comment by YusukeHirao** [comment]
It would help if you used `selector` with the attribute selector, or [`regexSelector`](https://markuplint.dev/configuration#properties/node-rules-&-child-node-rules/regex-selector).

```json
{
  "selector": "img",
  "rules": {
    "required-attr": [
      "alt"
    ]
  }
},
{
  "selector": "img:not([src$=.svg])",
  "rules": {
    "required-attr": [
      "alt",
      "srcset"
    ]
  }
}
```

**Comment by yamanoku** [comment]
👍👍👍👍👍
