### ISSUE TITLE
feature: angular markup parser

### ISSUE THREAD

**Issue by shrek-kurata** [markuplint/markuplint#456]
こちらが参考になります
https://github.com/rx-ts/markuplint

**Comment by shrek-kurata** [comment]
angularは属性ディレクティブという機能があって、htmlファイルでsrcではなく、[src]と記述することもできます。(動的にsrcになります）

required-attr: "src" | "[src]" みたいなことができればそれでいいですが、なさそうなのでparserを別途作って欲しいです

**Comment by YusukeHirao** [comment]
@shrek-kurata 

ご提案ありがとうございます。
https://github.com/rx-ts/markuplint があり、 `markuplint-angular-parser` としても公開されているので、そちらに頼っている状態なのですが、機会を見つけて取り組みたいとは思っています。ただ、今のところは優先順位があまり高くありません。

**Comment by JounQin** [comment]
Or maybe we can just link `markuplint-angular-parser` as 3rd-party `markuplint` parser in the README?

I'm not sure why it **should** be a built-in parser.
