### ISSUE TITLE
Replace monorepo tool

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#466]
- Lerna is dead
- https://turborepo.org/
- https://github.com/ghiscoding/lerna-lite
- https://efcl.info/2022/04/13/lerna-to-lerna-lite-and-turborepo/

**Comment by juristr** [comment]
Yep, we just released v5.0 yesterday and some cool features in v5.1 beta today: https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700?source=friends_link&sk=6c827ec7c9adfc1c760ff2e3f3e05cc7 🙂

**Comment by YusukeHirao** [comment]
@petamoriken  @juristr 

Wow, I just understand it now.
I can use Lerna to continue.
I will try to update it.
Thank you.
