### ISSUE TITLE
jsx-parser: Auto tag bind for styled-components styled CSS in JS

### ISSUE THREAD

**Issue by petamoriken** [markuplint/markuplint#471]
related: https://github.com/markuplint/markuplint/issues/468

CSS in JS, such as [styled-components](https://styled-components.com/), [emotion](https://emotion.sh/), and [linaria](https://linaria.dev/), can map JSX tags to HTML tags through clever parsing.

```jsx
const Button = styled.button`
  padding: 32px;
  background-color: hotpink;
  font-size: 24px;
  border-radius: 4px;
  color: black;
  font-weight: bold;
  &:hover {
    color: white;
  }
`;

export function CustomButton() {
  return <Button>This my button component.</Button>;
}
```

**Comment by YusukeHirao** [comment]
@petamoriken 

I wrote API ideas.
https://github.com/markuplint/markuplint/issues/468

Let me hear what you think.

**Comment by petamoriken** [comment]
If possible, I want to map JSX to HTML tags mechanically without preparing special files. I think it would be appropriate to support the parts that can be completed in a JSX file, and the parts that require module loading should be supported by the `pretenders` option.

**Comment by YusukeHirao** [comment]
@petamoriken 

Do you agree with what I assume as below?

If your example code:
1. Searches the variable `styled`.
2. Detects the member that is a tagged template.
3. It regards the member's name as a node name.
4. It regards the returned variable's name as a pretender's node name.
5. Creates a pretender object from these names.

We don't use JSX parser in only React. And may don't use styled-components and more. It is too difficult to infer the node pairing without a plugin hook.

Please tell me how do you parse and infer?

**Comment by petamoriken** [comment]
Probably some kind of JSX(TSX) parser will have to be used.

Linaria and Compiled use Babel to parse and convert JSX(TSX) files to achieve Zero-runtime CSS in JS. This may be helpful for implementation.
https://github.com/callstack/linaria/tree/master/packages/babel
https://github.com/atlassian-labs/compiled/tree/master/packages/babel-plugin

**Comment by YusukeHirao** [comment]
@petamoriken 

Thank you for your information.
I think may take a while but I will try it after I implement the `pretenders` option.
