### ISSUE TITLE
Add test case for `<transition>` to vue-parser specs

### ISSUE THREAD

**Issue by yamanoku** [markuplint/markuplint#482]
Vue.js has an API that can add transition effects (specifically, it adds transition CSS class).

ref: https://vuejs.org/guide/built-ins/transition.html

I'd like to add that the test case for markuplint does not test for the case where the element is included, so I would like to add it.

https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/vue-parser/src/index.spec.ts

**Comment by yamanoku** [comment]
```bash
<markuplint> error: HTMLの仕様において、要素「div」の内容は妥当ではありません (permitted-contents) 

  1: <template>
  2: ••<div class="hoge">
  3: ••••<transition•name="fade"•appear>```

When I tried this with the permitted-contents rule set to true, the above pattern resulted in an error.

```html
<template>
  <div class="hoge">
    <Transition•name="fade" appear>
```

However, when I listed `<Transition>` instead of `<transition>`, the element was removed from the checklist.

I had been writing transition elements with lowercase beginnings, but after consulting the documentation, it seems that it is okay to write them with uppercase letters.

**Comment by YusukeHirao** [comment]
@yamanoku 

The current evaluates an element as an HTMLElement if the name starts with the lower case and as a custom element if it begins with the upper case.

https://github.com/markuplint/markuplint/blob/0c774ce046ebc8a9c494e9884a4bfcd72a66250d/packages/%40markuplint/vue-parser/src/parse.ts#L202

I understand it is wrong to compute a Vue (or JSX) component as the custom element in Web Component.
It is issue #388 that I plan to resolve in the next version.

Could you tell me about the transition element?

- Whether there are particular elements else the element.
- What kind of element or document fragment does the Vue compiler convert the transition element to?
- Whether it can just evaluate its content model as transparent content on the permitted-content rule.

**Comment by yamanoku** [comment]
Thanks @YusukeHirao !

> It is issue https://github.com/markuplint/markuplint/issues/388 that I plan to resolve in the next version.

I hope this issue will be resolved and incorporated in the next version.

**Comment by yamanoku** [comment]
## Whether there are particular elements else the element.

As far as I am cognizant, elements other than `<Transition>` include the following.

- [`<component>`](https://vuejs.org/api/built-in-special-elements.html#component)
- [`<slot>`](https://vuejs.org/api/built-in-special-elements.html#slot)
- [`<TransitionGroup>`](https://vuejs.org/api/built-in-components.html#transitiongroup)
- [`<KeepAlive>`](https://vuejs.org/api/built-in-components.html#keepalive)
- [`<Teleport>`](https://vuejs.org/api/built-in-components.html#teleport)
- [`<Suspense>`](https://vuejs.org/api/built-in-components.html#suspense)
  - `<Suspense>` is an experimental feature. It is not guaranteed to reach stable status and the API may change before it does.

**Comment by yamanoku** [comment]
## What kind of element or document fragment does the Vue compiler convert the transition element to?

`<Transition>` element is not converted to a specific DOM, but is simply a function that assigns a transition class to a child element.

Please refer to the [documentation](https://vuejs.org/guide/built-ins/transition.html#the-transition-component) for details.

**Comment by yamanoku** [comment]
## Whether it can just evaluate its content model as transparent content on the permitted-content rule.

From [this comment](https://github.com/markuplint/markuplint/issues/482#issuecomment-1133585064), I think it is fine to treat it as a transparent content model, since it is not evaluated as a DOM element from anything.

**Comment by YusukeHirao** [comment]
@yamanoku 

I resolved this. See that PR.
