### ISSUE TITLE
In the svelte file "Error: The #text is invalid element" when marked up as ul> li> ul> li Broke mapping nodes. (parse-error) "is returned.

### ISSUE THREAD

**Issue by shamokit** [markuplint/markuplint#503]
初めてissueを投げるので失礼がありましたらすみません。

svelteファイル内で
ul>li>ul>liとマークアップしたときに

error: The #text is invalid element
Broke mapping nodes.(parse-error)になります。

試しにhtmlファイル内で同じhtmlを書いてみましたが、エラーにはならなかったので、
おそらく@markuplint/svelte-parser側の問題のようです。

**Comment by YusukeHirao** [comment]
@shamokit 

ご報告ありがとうございます。

具体的にソースコードを掲示できますか？
テキストや変数はダミーのものに変えていただいてで大丈夫なので、ソースコードと、行番号含んだエラーメッセージの詳細がほしいです。

**Comment by shamokit** [comment]
情報不足しておりすみません。

https://github.com/shamokit/test-markuplint
テストリポジトリを立てました。

ご確認よろしくお願い致します。

**Comment by YusukeHirao** [comment]
@shamokit 

リポジトリありがとうございます。
原因は改行コードのCRLFの可能性が高いです。
既知の問題ではあるのですが、内部的にパーサーとの兼ね合いで未解決です。
https://github.com/markuplint/markuplint/issues/31

HTMLで問題ないとのことですが、こちらはLFでしたか？

**Comment by YusukeHirao** [comment]
@shamokit 

あら、改行コードじゃないかったですか。
それは失礼しました。読みが外れました。
ソースコード確認しますね。
問題ないケースもブランチ作っていただいて非常に助かります。

**Comment by shamokit** [comment]
おそらく…

Mac環境で再現しないのであればWindows特有の現象とかなのかもしれないですね。

よろしくお願いします！

**Comment by YusukeHirao** [comment]
@shamokit 

確認してバグでしたので、修正しました。
https://github.com/markuplint/markuplint/releases/tag/v2.10.1 でリリースしていますのでご確認ください。

**Comment by shamokit** [comment]
ありがとうございます。

無事リントチェックが通りました！
お手数をおかけしました…！
