### ISSUE TITLE
How to use it on live url?

### ISSUE THREAD

**Issue by jitendravyas** [markuplint/markuplint#504]

**Comment by YusukeHirao** [comment]
Unfortunately, the CLI has no that.
You can only check the page if you download its HTML to your local.

I want to implement that it receives HTML through the pipe when cURL on the next version.

```sh
$ curl -s https://markuplint.dev | markuplint -c .markuplintrc
```

**Comment by YusukeHirao** [comment]
I noticed it was enabled originally, but it has a bug.

**Comment by YusukeHirao** [comment]
@jitendravyas 

Fixed in https://github.com/markuplint/markuplint/releases/tag/v2.10.1

You can do it if do the below:
```sh
$ curl -s https://markuplint.dev | markuplint -c .markuplintrc
```

please check.

**Comment by jitendravyas** [comment]
I get this error 
` error: RangeError: Maximum call stack size exceeded`

**Comment by jitendravyas** [comment]
I get this error 

<img width="914" alt="image" src="https://user-images.githubusercontent.com/77309/184547780-9d8c5596-afbf-45af-a8b9-e2e189032474.png">

**Comment by petamoriken** [comment]
Can we use an option to increase the stack size like `--stack_size=1200`?
https://stackoverflow.com/questions/11332422/how-can-i-increase-the-maximum-call-stack-size-in-node-js

**Comment by YusukeHirao** [comment]
@jitendravyas  Thanks for your report.

Could you tell me the byte size of your code evaluated?

markuplint doesn't support a huge code yet.
For example, it can't evaluate [HTML Standard One Page Version](https://html.spec.whatwg.org/) (1.8MB) on my machine.

I don't know the problem cause whether from the file size or the number of nodes.
I'm gonna add it as the new issue.
