### ISSUE TITLE
[astro-parser] `@astrojs/parser` is deprecated

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#574]
- Markuplint version: `2.11.0`
- @markuplint/astro-parser: `2.2.2`
- Parser lang: Astro

`@markuplint/astro-parser` depends on `@astrojs/parser` , 
https://github.com/markuplint/markuplint/blob/afa74b84894bec3ca633e25e5ea0ad3c0ee73209/packages/@markuplint/astro-parser/package.json

but `@astrojs/parser` is deprecated.
https://www.npmjs.com/package/@astrojs/parser/v/0.22.0

>⚠️ Notice @astrojs/parser has been deprecated. In previous versions of astro it was responsible for parsing .astro files. astro has since adopted the brand new [@astrojs/compiler](https://github.com/withastro/compiler).

Use `@astrojs/compiler` .
https://www.npmjs.com/package/@astrojs/compiler
https://github.com/withastro/compiler

**Comment by YusukeHirao** [comment]
I know it's.
But I can't upgrade it now because It needs ESM.
I will do that after getting ready for Markuplint's ESM upgraded.

Thank you for always;)
