### ISSUE TITLE
[website] Add new OG image

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#584]
There is no og:image in the website now.
(The og:image is not found in the current website and the new website)
https://markuplint.dev/
`og:image` url : https://repository-images.githubusercontent.com/104835801/27437480-da03-11e9-8504-c8407b7d9a13

@MirukaJP, Could you make OG image with the new logo for the website?

**Comment by MirukaJP** [comment]
@YusukeHirao @kagankan 

So, you need some layouts with space for optional text.
How about you make one Figma file for markuplint?

**Comment by YusukeHirao** [comment]
@MirukaJP @kagankan 

OK, I create a Figma project. I invite you all.

**Comment by YusukeHirao** [comment]
Done.
It's using imgix.
The domain is https://markuplint.imgix.net.

![Generated OG Image: Understanding Selector pages](https://markuplint.imgix.net/og-img-base.png?ixlib=js-3.7.0&mark=https%3A%2F%2Fmarkuplint.imgix.net%2F~text%3Fixlib%3Djs-3.7.0%26txt%3DUnderstanding%2520Selectors%26txt-align%3Dleft%252Cmiddle%26txt-color%3D333333%26txt-font%3DPT%2520Sans%252CBold%26txt-size%3D150%26txt-clip%3Dellipsis%26w%3D1600%26h%3D560&mark-x=240&mark-y=452&blend=https%3A%2F%2Fmarkuplint.imgix.net%2F~text%3Fixlib%3Djs-3.7.0%26txt%3DGuides%26txt-align%3Dcenter%252Cmiddle%26txt-color%3D000000%26txt-font%3DDIN%2520Alternate%252CBold%26txt-size%3D80%26txt-fit%3Dmax%26w%3D290%26bg%3DF4F4F4%26mask%3Dcorner%26corner-radius%3D20%252C20%252C20%252C20&blend-mode=normal&blend-x=240&blend-y=392&w=2400&h=1260)

Update [og-img-base.png](https://github.com/markuplint/markuplint/blob/main/website/static/img/og-img-base.png) if you want to change the background image.

**Comment by kagankan** [comment]
Nice! 👏👏

It's very easy to recognize what the page is.
In addition, cute and exciting 😍
It will be fun to post the URL!!
