### ISSUE TITLE
[website] Keep the pages for removed rules.

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#586]
In the new website, removed rule's page is deleted.

https://next.markuplint.dev/rules/attr-equal-space-after/ (Not found)

However, if we delete the page, there is no way to notice "this rule is removed" to users.

## Possible ways

Ways to manage removed rule docs:

1. keep only markdown files in  `packages/@markuplint/rules/[removed-rule]`
2. move doc files to `website/docs/rules/[removed-rule]`

If possible, I'd like to choose option `1`, because we can process the removed rules as same as living rules.
We can specify removed rule file with adding a property like `removed: true` to its frontmatter.

## Example: ESLint 

- We can access to the removed rule's page  
  - https://eslint.org/docs/latest/rules/generator-star/
- Removed rules are listed in `Removed` section
  - https://eslint.org/docs/latest/rules/#removed
  - but they don't have link.

**Comment by YusukeHirao** [comment]
I got it. I'll get ready 👍
