### ISSUE TITLE
Fix 3.0.0-rc.1 installation error

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#600]
- Markuplint version: `3.0.0-rc.1`
- Parser lang: HTML
- Node.js version: `v16.16.0`
- OS:  Windows

- npm version: `8.12.1`

## Describe the bug

I can't install markuplint 3.0.0-rc.1 with npm.

## Steps To Reproduce

exec `npm i markuplint@next`

```
PS C:\Users\Owner\Develop\markuplint-sample> npm i markuplint@next
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @markuplint/parser-utils@3.0.0-rc.1
npm WARN Found: peer @markuplint/ml-core@"3.x" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @markuplint/ml-core@"3.x" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @markuplint/ml-core@3.x.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Local\npm-cache\_logs\2022-12-03T04_53_23_026Z-debug-0.log
```

## Solutions

Fix the `ml-core` version in the peerDependencies 
https://github.com/markuplint/markuplint/blob/62d4d54bd9475670f618127de085a62480d6906d/packages/%40markuplint/parser-utils/package.json#L28

Or, notify temporary solutions to early adaptors.

## Temporary solutions

- Use yarn
- Use `npm i markuplint@next --legacy-peer-deps` to ignore peerDependencies

**Comment by YusukeHirao** [comment]
@kagankan 

Added about `--legacy-peer-deps` to https://github.com/markuplint/markuplint/releases/tag/v3.0.0-rc.1.
I have the early adaptor user use the option when installing.

Thank you.
