### ISSUE TITLE
[website] Include the rule-name in the page title

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#601]
I added Algolia search, but we cannot find some rule pages when we type their rule name.
For example, I typed `required-h1` but there are "Required elements" and "Rules" (list page) only, because the `required-h1` page doesn't have the string `required-h1` in its content or its title.

![image](https://user-images.githubusercontent.com/34136752/205436600-88e1fa11-951a-4206-9c17-3f06c0cce02c.png)

In many cases, users search with rule name to know more about the rule, I guess.
(In particular, when error results are displayed, the rule name is shown like `error: 要素「h1」が必要です (required-h1)` )

## Ideas

If you want to continue to include the description in the title, it should be 
`required-h1 (Level-one heading in document required)` (en) and
`required-h1 （ドキュメント内の h1 必須）` (ja)
However, it's a little too long for title.

I prefer to use only the rule name like
`required-h1` (same in Japanese or other languages)
ESLint and Stylelint are also using this style
https://eslint.org/docs/latest/rules/array-callback-return
https://stylelint.io/user-guide/rules/no-descending-specificity

**Comment by YusukeHirao** [comment]
@kagankan 

Yes, you are right.
I'll improve. I link PR #602.
