### ISSUE TITLE
Shouldn't `option` be `options` ?

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#604]
Sorry to ask about such minor details. 🙏

The name of the property for configuring rule details is `option` (singular form)

```
{
  "rules": {
    "rule-name": {
      "option": {
      }
    }
  }
}
```

I've been felt unnatural about it.
Shouldn't it  be **`options`** (plural form)?

Other config properties (like `parserOptions`) are also plural.
https://next.markuplint.dev/configuration/#properties/parser-options

In addition, its heading in doc is `Options` 
https://next.markuplint.dev/rules/landmark-roles/#options

**Comment by YusukeHirao** [comment]
TODO: Update documents #602
