### ISSUE TITLE
Move `community` pages

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#613]
From #602

> The pages of branding, contributing, community should be in src/pages directory, I think.
> They are independent from package's features or versions.
> (* while writing this, I found src/pages/something.md occurs error. I'll send a PR later.)
> 
> If you would like to use sidebars for these pages, you can customize directory for docs as Docusaurus' website does.
https://github.com/facebook/docusaurus/blob/eecfdebf084facca78b4c9074566df4109dadd5d/website/docusaurus.config.js#L163

**Comment by YusukeHirao** [comment]
@kagankan 

:warning: MEMO:
I created the hook to generate the OG image.
This file may affect just docs.
Be careful; extracting a title on each page is complex.
https://github.com/markuplint/markuplint/blob/3c5d969bdf380cd6aa4b1feabae4fd01054d1535/website/src/theme/DocPage/index.tsx#L17-L29

**Comment by kagankan** [comment]
OK.
I'll look into ways to apply og image to pages.

**Comment by YusukeHirao** [comment]
It probably relates to #623.
