### ISSUE TITLE
インラインSVGでタグ全てに`require-accessible-name`のエラーが出る

### ISSUE THREAD

**Issue by spicato-kanayama** [markuplint/markuplint#644]
- Markuplint version: 3.0.0
- Parser lang: HTML
- Node.js version: v18.12.1
- OS: macOS

## Describe the bug
タイトルの通り、インラインSVGでタグ全てに`require-accessible-name`のエラーが出ます。
svgタグに`aria-label`を付与しても解消しませんでした。

HTMLの仕様で全てにアクセシブルな名前が必要なのでしょうか？？

## Code Example

```html
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" >
<g clip-path="url(#clip0_345_2)">
	<path d="M0 10.4727H10.384" stroke="black" stroke-width="2" />
	<path d="M14.562 10.472L9.36201 15.446V5.49902L14.562 10.472Z" fill="black" />
	<path d="M4.77295 6.99902V0.999023H18.6189V18.999H4.77295V13.999" stroke="black" stroke-width="2" />
</g>
<defs>
	<clipPath id="clip0_345_2">
		<rect width="19.615" height="20" fill="black" />
	</clipPath>
</defs>
</svg>
```

## Steps To Reproduce

1.
2.

**Comment by YusukeHirao** [comment]
@spicato-kanayama 


[ARIA Graphics Module](https://w3c.github.io/graphics-aria/)とWAI-ARIAの仕様で必要になりますが、
結論から言うと、`<svg>`要素に`role="img"`を付与することで解決します。

解説が少々ややこしくなりますが、順に説明しますと、

- `<svg>`配下の要素（`<path>`など）はロールが`graphics-symbol`
- [`graphics-symbol`ロール](https://w3c.github.io/graphics-aria/#graphics-symbol)はアクセシブルな名前が**必須**
- `<svg>`要素自体はロールが`graphics-document`
- `graphics-document`は[Children Presentational](https://momdo.github.io/wai-aria-1.2/#childrenArePresentational)がfalseなため、子孫要素はアクセシビリティツリーに公開されるため、それぞれにアクセシブルな名前が要求される

ここまでが、現状、要求されている理由です。
そして、`<svg>`要素に`role="img"`を付与することで解決理由は以下の通りになります。

- `<svg>`要素に`role="img"`を付与すると、許可されたロールなのでロールは`img`となる
- `img`は[Children Presentational](https://momdo.github.io/wai-aria-1.2/#childrenArePresentational)がtrueなため、子孫要素はアクセシビリティツリーに公開されないことになり、それぞれにアクセシブルな名前は不要となる

**Comment by spicato-kanayama** [comment]
@YusukeHirao 
ご丁寧にありがとうございます！！！
