### ISSUE TITLE
End of support Node.js v14

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#670]
Node.js v14 until 30 Apr 2023.
Change to **Support v16.10.x or later**

- [x] Switch test CI to v16
- [ ] Update Syntaxes in [ES](https://node.green/)
  - [spread parameters after optional chaining](https://github.com/tc39/proposal-optional-chaining) since v16.3
  - [String.prototype.replaceAll](https://github.com/tc39/proposal-string-replace-all) since v15
  - [numeric separators](https://github.com/tc39/proposal-numeric-separator) since v15
  - [`Promise.any`](https://github.com/tc39/proposal-promise-any) since v15
  - [WeakReferences](https://node.green/#ES2021-features-WeakReferences) since v14.21
  - [Logical Assignment](https://node.green/#ES2021-features-Logical-Assignment) since v15
  - [optional private instance class fields access](https://github.com/tc39/proposal-class-fields) since v14.21
  - [optional deep private instance class fields access](https://github.com/tc39/proposal-class-fields) since v14.5
  - [private class methods](https://node.green/#ES2022-features-private-class-methods) since v14.21
  - [.at() method on the built-in indexables](https://node.green/#ES2022-features--at---method-on-the-built-in-indexables) since v16.8
  - [Object.hasOwn](https://node.green/#ES2022-features-Object-hasOwn) since v16.10
  - [Error.cause property](https://node.green/#ES2022-features-Error-cause-property) since v16.10
  - [RegExp Match Indices (`hasIndices` / `d` flag)](https://node.green/#ES2022-features-RegExp-Match-Indices---hasIndices-----d--flag-) since v16.0
- [ ] Update Dependencies
  - [ ] `jsdom` 21 -> 22 ([Failed Test](https://github.com/markuplint/markuplint/actions/runs/4891579491/jobs/8732363884?pr=977))

**Comment by munierujp** [comment]
Node v14 has already reached EOL. How is the progress?

**Comment by YusukeHirao** [comment]
@munierujp 

I'm planning to gradually start working on the v4 branch soon.
