### ISSUE TITLE
Lint string instead of file?

### ISSUE THREAD

**Issue by iamallyniam** [markuplint/markuplint#671]
In the api, is it possible to pass a string instead of a path to a file? Looking through the [api documentation](https://markuplint.dev/docs/api/classes) only passing a file is mentioned. There are a lot of scenarios where passing a string would be more useful than a file, in my case I don't output any HTML files and would like to lint Nunjucks changes whilst running the dev server.

**Comment by YusukeHirao** [comment]
Please use `MLEngine.toMLFile` function.

```ts
const file = await MLEngine.toMLFile({
  name: 'FILE_NAME__OPTIONAL',
  workspace: 'WORKING_DIRECTORY__OPTIONAL',
  sourceCode: `<html>
    <head>...</head>
    <body>...</body>
  </html>`,
});

const engine = new MLEngine(file, {
  config: {
    parser: {
      '.njk$': '@markuplint/nunjucks-parser',
    },
  },
});

const result = await engine.exec();
```

Sorry, the API documentation is written in progress.

**Comment by iamallyniam** [comment]
Thanks @YusukeHirao that's just what I needed to know.
