### ISSUE TITLE
Cannnot test with `markuplintrc.js` file

### ISSUE THREAD

**Issue by ysksms** [markuplint/markuplint#677]
- Markuplint version: `v3.1.0`
- Parser lang: JSX
- Node.js version: `v18.6.0`
- OS: macOS

## Describe the bug

markuplint does not perform a test correctly when using `markuplintrc.js` file.

According to the  [documentation](https://markuplint.dev/ja/docs/configuration#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%BD%A2%E5%BC%8F%E3%81%A8%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D), we can use  `markuplintrc.js` for configs and  rule settings.

But  by using  `markuplintrc.js` file,
test ends very shortly with no errors even though  there are some errors in code.

※ We can  perform a test correctly using `markuplint.config.js` even though the descriptions in `markuplintrc.js`   and  `markuplint.config.js` are totally same. (the only difference is file name)

## Additional Information

By using the file`.markuplintrc.js`, we can  perform a test correctly.  (added `.` to the file name)

・`markuplintrc.js` →  test doesn't  runs expectedly.
・`.markuplintrc.js` →  test runs expectedly.

**Comment by YusukeHirao** [comment]
@ysksms Thank you for your reporting.

I'm sorry. It's just a typo.
Markuplint's configuration depends [cosmiconfig](https://github.com/davidtheclark/cosmiconfig#explorersearch), so **prepending a dot** is correct.

I'll rewrite a document.
