### ISSUE TITLE
The languages selection menu has the keyboard manipulating bug

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#700]
![Screen shot: languages selection menu](https://user-images.githubusercontent.com/953956/218093351-d9863f24-3572-4c17-afcb-a7490cc7283f.png)

It throws a JavaScript error when I go back to an item by manipulating the shift key with the tab key, then the menu disappears.

**Comment by kagankan** [comment]
I sent a PR to Docusaurus, and it has been merged.
https://github.com/facebook/docusaurus/pull/8699

It will be fixed in an update soon.

**Comment by YusukeHirao** [comment]
@kagankan 

It was fixed after I upgraded Docusaurus.
Thank you!
