### ISSUE TITLE
Include "HTML" in the description

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#714]
# Goal

- Make it easy for those who need Markuplint to find it.
- Make it easy to understand what Markuplint does.

# Background

Developers who want to check the syntax of HTML would search for the search word [HTML Linter].
However, if we do a Google search on that word, Markuplint's website finally appears on **page 6**.
https://www.google.com/search?q=html+linter&hl=en

Screenshot:
![image](https://user-images.githubusercontent.com/34136752/219144429-1608d0b5-9762-4e8a-8e3a-84c7be2f92fa.png)

I would like to make Markuplint's site rank on the first page.

# Proposal

If "HTML" is included in the description, it can properly describe the purpose of the Markuplint.
This would also improve SEO.

Before:
`A linter for all markup developers`
![image](https://user-images.githubusercontent.com/34136752/219144706-7d453361-2200-4f80-9761-bc331099d18a.png)

↓
After:
**`A HTML linter for all markup developers`**

# References: Other linters

## ESLint
>Find and fix problems in your **JavaScript** code
https://eslint.org/

## Stylelint

>A mighty **CSS** linter that helps you avoid errors and enforce conventions.
https://stylelint.io/

## TSLint
>An extensible linter for the **TypeScript** language.
https://palantir.github.io/tslint/

Please consider it!🙏

**Comment by YusukeHirao** [comment]
@kagankan Thank you!

It is a nice idea.
Could you PR?

A linter for all markup developers
↓
An HTML linter for all markup developers

すべてのマークアップ開発者のためのリンター
↓
すべてのマークアップ開発者のためのHTMLリンター
