### ISSUE TITLE
Renewal Playground

### ISSUE THREAD

**Issue by kagankan** [markuplint/markuplint#734]
Continued from #214

Renewal playground website.
https://playground.markuplint.dev/

## Planning features

- [ ] Merge it into the main website (markuplint.dev).
  - in order to make it easier to navigate around the website.
- [ ] Show the rules of the currently applied configuration. 
- [ ] Allow users to select rules with GUI.
- [ ] Allow users to resize each pane.
- [ ] Show the errors and the warnings.
- [ ] Add some examples (e.g. BEM pattern class-naming config)

## Screenshot of the draft PR by @YusukeHirao 

![スクリーンショット_20230223_002408](https://user-images.githubusercontent.com/34136752/220907865-cf8b5ffe-f39b-4371-ac15-89050fc42981.png)

**Comment by YusukeHirao** [comment]
@kagankan 

I have a selfish. May I ask you a favor?
I want to adopt Tailwind CSS.
What do you think?

**Comment by kagankan** [comment]
@YusukeHirao 

Thanks for your comment!

First of all, I am considering putting the playground page into the main website. (See my draft PR #741)
Do you agree with this?
If we adopt this, and we install Tailwind CSS, we would have to install it to the website (not only the playground), is that still acceptable?

I do like Tailwind CSS, but I don't like the "utility-first" approach.
I prefer to write plain CSS.
I usually use Tailwind CSS only as supportive utilities.
So, I install it if we adopt it only as supportive utilities.
Would that still be OK?

**Comment by YusukeHirao** [comment]
@kagankan 

> First of all, I am considering putting the playground page into the main website. (See my draft PR https://github.com/markuplint/markuplint/pull/741)
> Do you agree with this?

I'm wondering whether merging the playground.

- The playground depends on Markuplint packages.
- The main site doesn't depend on those.
- I want to think carefully about whether it affects CI, deploying, Lerna, and Yarn Workspaces. (But I may worry too much)

And I want features the following to the playground:

- Accessibility preferences
  - The live region settings.
  - Switching Light/Dark mode or code highlighting themes.
- Import/Export configuration
- Switching Template engines
- Fetching HTML string from URL (If it is abled)

I worry whether it can coexist with Docusaurus because the playground is one web application.
I know that is abled but I worry about maintenance.

Let us discuss adopting Tailwind after this is resolved.

**Comment by kagankan** [comment]
@YusukeHirao 

Your concerns are certainly understandable.

The benefits of merging that I expect are as follows:

- (For maintainers) Lower maintenance costs because we can use Docusaurus features such as switching between light/dark mode
- (For users) Common header makes it easier to navigate between pages.

Speaking of package management, I am planning to refer to Markuplint package **WITHOUT** the yarn workspaces.
For example, the website of ESLint adopts this approach.

- Its repository is separated from core eslint package repository.
- It has playground page (inside the main website).
- The playground page refers to the latest version of eslint package from npm.
  - https://github.com/eslint/eslint.org/blob/main/src/playground/package.json

(However, ESLint is **NOT** a Docusaurus site, so it is not helpful in that regard.)

As for problems caused by coexistence, I don't think they'll happen,
but we never really know until we try...
Therefore, I understand the opinion that it should be an independent application.

Would you give me your thoughts? 👀

**Comment by kagankan** [comment]
I am planning to use the Stylelint Demo's structure as a reference.
https://stylelint.io/demo/
https://github.com/stylelint/stylelint-demo

- Embed an independent application in an iframe in the Docusaurus site
- Use web container API
  - https://github.com/stylelint/stylelint-demo/issues/351
