### ISSUE TITLE
Don't use "any-rule" in the document

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#764]
https://markuplint.dev/docs/guides/ignoring-code

**Comment by petamoriken** [comment]
The rule "any-rule" was sometimes mistaken for an actual rule. It needs to be a different placeholder like "[[any-rule]]" or an example with actual rules.

**Comment by YusukeHirao** [comment]
@satishkumarsajjan Thank you for your question. That is just as he explained it.

@petamoriken Thanks for your follow-ups.
