### ISSUE TITLE
Delete noreferrer check for `target="_blank"`

### ISSUE THREAD

**Issue by petamoriken** [markuplint/markuplint#765]
[All modern browsers support noopener](https://caniuse.com/rel-noopener), so we need not to use noreferrer for fallbacks.
Perhaps we need not to check noopener too because [target="_blank" implies rel="noopener" behavior (except Opera)](https://caniuse.com/mdn-html_elements_a_implicit_noopener).

related: https://twitter.com/pentaprogram/status/1639121192673218560

**Comment by YusukeHirao** [comment]
Note for me:

- [ ] Remove Code
- [ ] Remove from documents

https://github.com/markuplint/markuplint/blob/2bc27ead94e556a8f4d6e91b9c37312b256946cf/packages/%40markuplint/config-presets/src/preset.security.json#L3-L21
