### ISSUE TITLE
Ignore `node_modules` directory by default

### ISSUE THREAD

**Issue by munierujp** [markuplint/markuplint#766]
The current recommended configuration detects a lot of errors in files located under the `node_modules` directory.

<img width="1231" alt="スクリーンショット 2023-03-24 22 47 48" src="https://user-images.githubusercontent.com/20086673/227538542-c0a5d89a-5ad8-4a01-a11a-fbac76034861.png">

How about ignoring the `node_modules` directory by default, as in [ESLint](https://eslint.org/docs/latest/use/configure/ignore#the-eslintignore-file) and [stylelint](https://stylelint.io/user-guide/configure/#ignorefiles)?

**Comment by YusukeHirao** [comment]
It has no ignoring `node_modules` by default.

So you should specify `"./node_modules/**/*"` to the `excludefiles` property.
https://markuplint.dev/docs/configuration/properties#excludefiles

I consider I improve to ignore `node_modules`, thank you.

**Comment by YusukeHirao** [comment]
Add the option `--future-ignore-node-modules` to v3.

In v4, enable it by default. And add `--include-node-modules` and remove `--future-ignore-node-modules`.
