### ISSUE TITLE
How about using `lint:html` instead `html:lint` in npm scripts?

### ISSUE THREAD

**Issue by munierujp** [markuplint/markuplint#773]
Currently, the documentation shows sample code that defines a script called `html:lint` in npm scripts.

https://github.com/markuplint/markuplint/blob/3ee2ad08af32dec35b099a37752b11cecfa2baf4/website/docs/guides/index.md?plain=1#L37

How about using `lint:html` instead `html:lint`?
Defining a script like `lint:html` in npm scripts has following advantages:

- [`lint:html`](https://github.com/search?q=path%3Apackage.json+%22lint%3Ahtml%22&type=code&ref=advsearch) is used in more repositories than [`html:lint`](https://github.com/search?q=path%3Apackage.json+%22html%3Alint%22&type=code&ref=advsearch)
- Can be run with scripts such as `lint:js` and `lint:css` with [npm-run-all2](https://www.npmjs.com/package/npm-run-all2)

Example:

```json
{
  "scripts": {
    "lint": "npm-run-all -p lint:*",
    "lint:css": "stylelint '**/*.css'",
    "lint:html": "markuplint \"**/*.html\"",
    "lint:js": "eslint --ext .js,.html --ignore-path .gitignore ."
  },
  "devDependencies": {
    "eslint": "8.36.0",
    "markuplint": "3.5.0",
    "npm-run-all2": "6.0.4",
    "stylelint": "15.3.0"
  }
}
```

**Comment by YusukeHirao** [comment]
@munierujp 

Thanks for letting me know. It's good.
Would you pull request?

**Comment by munierujp** [comment]
@YusukeHirao I'll do it 😎
