### ISSUE TITLE
Fix `no-empty-palpable-content` warning on `<pre>` element

### ISSUE THREAD

**Issue by SaekiTominaga** [markuplint/markuplint#775]
- Markuplint version: `3.5.0`
- Parser lang: HTML
- Node.js version: `18.12.0`
- OS: Windows

## Describe the bug

If the text in a `<pre>` element has line breaks or indentation, some combination of these will trigger a `no-empty-palpable-content` warning.

## Code Example

```json
{
  "rules": {
    "no-empty-palpable-content": true
  }
}
```

```html
<!-- ↓ no errors 😄 -->
<pre>text</pre>

<!-- ↓ no errors 😄 -->
<pre>
  text</pre>

<!-- ↓ no errors 😄 -->
<pre>text
text</pre>

<!-- ↓ warning: 要素は空しないほうがよいです (no-empty-palpable-content) 😥 -->
<pre>
text</pre>
```

**Comment by YusukeHirao** [comment]
Info: https://html.spec.whatwg.org/multipage/syntax.html#element-restrictions
