### ISSUE TITLE
Fix URL encode & HTML escape bug in `no-refer-to-non-existent-id`

### ISSUE THREAD

**Issue by SaekiTominaga** [markuplint/markuplint#776]
- Markuplint version: `3.5.0`
- Parser lang: HTML
- Node.js version: `18.12.0`
- OS: Windows

## Describe the bug

If the anchor's `href` attribute value is URL encoded, or if the ID is HTML escaped, cannot find ID.

## Code Example

```json
{
  "rules": {
    "no-refer-to-non-existent-id": true
  }
}
```

```html
<!-- ↓ error: "apple%3Aorange" IDがありません (no-refer-to-non-existent-id) -->
<a href="#apple%3Aorange">apple:orange</a>
<p id="apple:orange">apple:orange</p>

<!-- ↓ error: "apple%26orange" IDがありません (no-refer-to-non-existent-id) -->
<a href="#apple%26orange">apple&amp;orange</a>
<p id="apple&amp;orange">apple&amp;orange</p>
```

\* `%3A`=`:`, `%26`=`&`

## URL encode

https://github.com/markuplint/markuplint/blob/3ee2ad08af32dec35b099a37752b11cecfa2baf4/packages/%40markuplint/rules/src/no-refer-to-non-existent-id/index.ts#L194-L196

`decodeURI` → `decodeURIComponent`

## HTML escape

https://github.com/markuplint/markuplint/blob/3ee2ad08af32dec35b099a37752b11cecfa2baf4/packages/%40markuplint/rules/src/no-refer-to-non-existent-id/index.ts#L32-L34

Need to unescape `attr.value`.

**Comment by himanoa** [comment]
May I try this?
