### ISSUE TITLE
If the result does not contain any errors, please return `0` as exit code

### ISSUE THREAD

**Issue by munierujp** [markuplint/markuplint#779]
Currently, if the result does contain **warnings**, `1` is returned as the exit code even if the result does not contain any **errors**.
The "**warning**" is only a reminder message, and it would be strange for it to cause the CI execution to fail.
For example, in ESLint, the exit code is `0` if there is a **warning** but no **error**.

If the result does not contain any **errors**, please return `0` as exit code.

**Comment by YusukeHirao** [comment]
@munierujp 

Thank you for the excellent advice.

However, the behavior is a breaking change as CLI.
I will implement it in v4 because I want to adopt it.
