### ISSUE TITLE
How about supporting TypeScript for config file?

### ISSUE THREAD

**Issue by munierujp** [markuplint/markuplint#797]
Writing configuration files in TypeScript is useful in preventing typographical and type errors.

```ts
import type { Config } from '@markuplint/ml-config'

const config: Config = {
  extends: [
    'markuplint:recommended'
  ],
  excludeFiles: [
    './node_modules/**/*'
  ]
}

export default config
```

In [cosmiconfig](https://www.npmjs.com/package/cosmiconfig), TypeScript is supported  by the third-party [cosmiconfig-typescript-loader](https://www.npmjs.com/package/cosmiconfig-typescript-loader).
How about supporting TypeScript for config file?

**Comment by YusukeHirao** [comment]
@munierujp 

Good idea, thanks for sharing.
But it's not a top priority for me, so can you handle it and send a pull request?

**Comment by munierujp** [comment]
@YusukeHirao I will do it.
