### ISSUE TITLE
`*.erb` support

### ISSUE THREAD

**Issue by yamanoku** [markuplint/markuplint#85]
I'm running a monolithic Rails application at work. I'm trying to have the front end responsibilities on the front side, but I don't think I can do that yet and I think some of it will remain.

I think many people would be happy if erb files were also subject to markuplint 🙏 

https://markuplint.dev/setting-for-other-languages

**Comment by YusukeHirao** [comment]
@yamanoku 

I have a question about the eRuby template syntax so do you tell me that.

I saw https://magazine.rubyist.net/articles/0017/0017-BundledLibraries.html,
but I don't feel like I quite understand.
Do you use the line that started "%" or "%%"?

**Comment by yamanoku** [comment]
@YusukeHirao 

Hmm, I've never seen that writing started "%" or "%%" style by eRuby.

Basically, I use `<% ... %>` to start the definition, or write the HTML tags as is as a partial file in the eRuby file.

**Comment by YusukeHirao** [comment]
@yamanoku 

Thank you for an answer.
I've decided don't support the line that started "%" yet.
