### ISSUE TITLE
Support of multiple files for scanning

### ISSUE THREAD

**Issue by ChristianStornowski** [markuplint/markuplint#9]
It would be nice if i could use a package.json script like:

`"markuplint": "markuplint \"./src/**/*.html\""`

**Comment by YusukeHirao** [comment]
@ChristianStornowski  Thank you for propose. I'm sorry for my late reply, I was in vacation.
Please look it because it was implemented immediately.

https://github.com/markuplint/markuplint/commit/d472bedd46753de8bec1393312d58c52cdaf91ce

**Comment by ChristianStornowski** [comment]
Thanks. It's working. :-)
