### ISSUE TITLE
[website] `@markuplint/html-spec` link URL are not unified

### ISSUE THREAD

**Issue by SaekiTominaga** [markuplint/markuplint#904]
https://markuplint.dev/docs/rules/deprecated-attr
https://markuplint.dev/docs/rules/deprecated-element
https://markuplint.dev/docs/rules/permitted-contents
→https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/index.json

https://markuplint.dev/docs/rules/invalid-attr
→https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/html-spec/src

https://markuplint.dev/docs/rules/required-attr
→https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/html-spec/src/attributes (404)

https://markuplint.dev/docs/rules/wai-aria
→https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/html-spec/src/aria-in-html (404)

Which is correct? (`index.json` ?)

**Comment by YusukeHirao** [comment]
@SaekiTominaga 

Thanks! I'll fix those.
