### ISSUE TITLE
Clarify `minimatch` is used to parse `excludeFiles` of configuration files in docs

### ISSUE THREAD

**Issue by risu729** [markuplint/markuplint#927]
In [`excludeFiles` section](https://markuplint.dev/docs/configuration/properties#excludefiles) in the docs, it doesn't clarify which library or syntax should be used.

It seems markuplint uses minimatch to parse glob patterns of `excludeFiles`.
https://github.com/markuplint/markuplint/blob/c2c06ab5f8d19e2b2d6dcaea258bdc652f8eaae7/packages/%40markuplint/file-resolver/src/ml-file/ml-file.ts#L92-L94

I think clarifying the library helps in writing complex patterns.
However, if it's clarified once, it might be difficult to change the library to keep the backward compatibility.
If it would not be a problem, I would like to send a PR.

e.g. [ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#specifying-files-and-ignores)
![CE4CF65C-2619-45E5-B8BC-E312EC3AF4FA](https://user-images.githubusercontent.com/79110363/235294185-95870b40-cfea-4e29-b742-c6040ee829be.jpeg)

**Comment by YusukeHirao** [comment]
@risu729 

Thank you for bringing up this interesting issue. You're right, it might be better to clarify that part. However, not only `minimatch` but also [`glob`](https://www.npmjs.com/package/glob) is used in some parts for handling the Glob format, so it seems necessary to take some time to identify and organize those parts.

**Comment by YusukeHirao** [comment]
@risu729 

It seems that `glob` is using `minimatch` indeed. Mentioning that it uses `minimatch` should be fine. If you could submit a PR, I'd really appreciate it. It would be very helpful.

**Comment by risu729** [comment]
@YusukeHirao

Thank you so much for your response.
I was looking into the usage of `minimatch` and `glob`. JFYI, it seemed `minimatch` is used in configurations and `glob` is used in CLI.
I would submit a PR soon.
