### ISSUE TITLE
Fix deprecated @types packages

### ISSUE THREAD

**Issue by regseb** [markuplint/markuplint#947]
- Markuplint version: `3.9.0`
- Node.js version: `v18.16.0`
- OS: Ubuntu 22.04.2 LTS

## Describe the bug

Markuplint has deprecated type dependencies because the packages _provide its own type definitions, so you do not need this installed._

- [`@types/cosmiconfig`](https://github.com/search?q=repo%3Amarkuplint%2Fmarkuplint%20%40types%2Fcosmiconfig&type=code): [`cosmiconfig`](https://www.npmjs.com/package/cosmiconfig)
- [`@types/meow`](https://github.com/search?q=repo%3Amarkuplint%2Fmarkuplint+%40types%2Fmeow&type=code): [`meow`](https://www.npmjs.com/package/meow)
- [`@types/has-yarn`](https://github.com/search?q=repo%3Amarkuplint%2Fmarkuplint+%40types%2Fhas-yarn&type=code): [`has-yarn`](https://www.npmjs.com/package/has-yarn)

## Code Example

```JSON
{
    "name": "testcase",
    "version": "1.0.0",
    "private": true,
    "dependencies": {
        "markuplint": "3.9.0"
    }
}
```

## Steps To Reproduce

1. `npm install`

## The current behavior

```
npm WARN deprecated @types/cosmiconfig@6.0.0: This is a stub types definition. cosmiconfig provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/meow@6.0.0: This is a stub types definition. meow provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/has-yarn@1.0.1: This is a stub types definition. has-yarn provides its own type definitions, so you do not need this installed.

added 266 packages, and audited 267 packages in 6s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

## The expected behavior

No warning.

**Comment by YusukeHirao** [comment]
@regseb

Thank you for the input. Unfortunately, each main package can't be updated because the latest version is only distributed in ESM format. So I cannot remove them right now. If you have any good solutions, I'd appreciate it if you could share them with me.

**Comment by YusukeHirao** [comment]
It will be resolved in v4.

**Comment by ZuBB** [comment]
> It will be resolved in v4.

Thanks a lot for this news, but why close the task if v4 is not available yet?

**Comment by YusukeHirao** [comment]
@ZuBB 

You can try alpha https://github.com/markuplint/markuplint/releases/tag/markuplint%404.0.0-alpha.5
Please try it.

**Comment by ZuBB** [comment]
> @ZuBB
> 
> You can try alpha https://github.com/markuplint/markuplint/releases/tag/markuplint%404.0.0-alpha.5 Please try it.

I gave it a quick try. No deprecated types. All works OK for me. 

Thanks a lot for this tool
